# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HTT America | Hi Tech Tilt America | Tilt Up Concrete Construction
email: info@httamerica.com
description: > # this means to ignore newlines until "baseurl:"
  Hi-Tech Tilt™ is the technology breakthrough of a 16ga. structural metal stud combined with W.M.F. steel reinforcement embedded in a standard 2″ concrete slab used in both floors, & walls (with load bearing capabilities). Hi-Tech Tilt™ is a patented composite building technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vooshi.com/clients/htt" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ["gulpfile.js",
					"node_modules",
					"package.json"]